In [71]:
# Initial imports.
import pandas as pd
import numpy as np
# from path import Path
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [18]:
# Import our input dataset
url = 'https://raw.githubusercontent.com/Lalita-ponnapalli/HS_Baseball_Scholarships/main/allstudentactivities1718final.csv'
schdist_df = pd.read_csv(url)
schdist_df.head()

id     year    revtotal  member  overallaccountscore  activitysum  \
0   7  2017-18  9963425.41     771                 76.3     553604.0   
1   7  2017-18  9963425.41     771                 76.3     553604.0   
2   7  2017-18  9963425.41     771                 76.3     553604.0   
3   7  2017-18  9963425.41     771                 76.3     553604.0   
4   7  2017-18  9963425.41     771                 76.3     553604.0   

   revperstudent  diststudachievescore  diststudentgrowthscore  pctlep  ...  \
0   12922.730752                  50.6                    69.9   0.308  ...   
1   12922.730752                  50.6                    69.9   0.308  ...   
2   12922.730752                  50.6                    69.9   0.308  ...   
3   12922.730752                  50.6                    69.9   0.308  ...   
4   12922.730752                  50.6                    69.9   0.308  ...   

   pctecondisad  insttype  largegroupby  groupbyvalue groupcount studentcount  \
0         0.685    Public  All Students  All Students         31           12   
1         0.685    Public  All Students  All Students         31            6   
2         0.685    Public  All Students  All Students         31            4   
3         0.685    Public  All Students  All Students         31            3   
4         0.685    Public  All Students  All Students         31            1   

                      schoolname   initenroll   instloc instlevel  
0  Abbotsford Middle/Senior High   First Fall  In-State    2-Year  
1  Abbotsford Middle/Senior High   First Fall  In-State    4-Year  
2  Abbotsford Middle/Senior High   First Fall  In-State  Multiple  
3  Abbotsford Middle/Senior High  Second Fall  In-State    2-Year  
4  Abbotsford Middle/Senior High  Second Fall  In-State    4-Year  

[5 rows x 22 columns]

In [19]:
schdist_df = schdist_df.drop(columns=['year', 'schoolname', 'id', 'largegroupby', 'groupbyvalue', 'insttype'])

In [20]:
# Create LabelEncoder instance
labelencoder = LabelEncoder()

# Encode 'initenroll' column
schdist_df['initenrollcode'] = labelencoder.fit_transform(schdist_df['initenroll'])
schdist_df = schdist_df.drop(columns=['initenroll'])
schdist_df

revtotal  member  overallaccountscore  activitysum  revperstudent  \
0      9963425.41     771                 76.3     553604.0   12922.730752   
1      9963425.41     771                 76.3     553604.0   12922.730752   
2      9963425.41     771                 76.3     553604.0   12922.730752   
3      9963425.41     771                 76.3     553604.0   12922.730752   
4      9963425.41     771                 76.3     553604.0   12922.730752   
...           ...     ...                  ...          ...            ...   
4365  15548503.74    1325                 84.2    1120235.0   11734.719804   
4366  15548503.74    1325                 84.2    1120235.0   11734.719804   
4367  15548503.74    1325                 84.2    1120235.0   11734.719804   
4368  15548503.74    1325                 84.2    1120235.0   11734.719804   
4369  15548503.74    1325                 84.2    1120235.0   11734.719804   

      diststudachievescore  diststudentgrowthscore  pctlep  pctwhite  pctswd  \
0                     50.6                    69.9   0.308     0.493   0.130   
1                     50.6                    69.9   0.308     0.493   0.130   
2                     50.6                    69.9   0.308     0.493   0.130   
3                     50.6                    69.9   0.308     0.493   0.130   
4                     50.6                    69.9   0.308     0.493   0.130   
...                    ...                     ...     ...       ...     ...   
4365                  88.1                    73.6   0.050     0.876   0.102   
4366                  88.1                    73.6   0.050     0.876   0.102   
4367                  88.1                    73.6   0.050     0.876   0.102   
4368                  88.1                    73.6   0.050     0.876   0.102   
4369                  88.1                    73.6   0.050     0.876   0.102   

      pctecondisad  groupcount  studentcount       instloc instlevel  \
0            0.685          31            12      In-State    2-Year   
1            0.685          31             6      In-State    4-Year   
2            0.685          31             4      In-State  Multiple   
3            0.685          31             3      In-State    2-Year   
4            0.685          31             1      In-State    4-Year   
...            ...         ...           ...           ...       ...   
4365         0.200         100             3      Multiple  Multiple   
4366         0.200         100             4  Out-of-State    4-Year   
4367         0.200         100             1      In-State    2-Year   
4368         0.200         100             1      In-State    4-Year   
4369         0.200         100             6      In-State    2-Year   

      initenrollcode  
0                  0  
1                  0  
2                  0  
3                  2  
4                  2  
...              ...  
4365               0  
4366               0  
4367               1  
4368               1  
4369               2  

[4370 rows x 16 columns]

In [21]:
# Encode 'instlevel' column
schdist_df['instlevelcode'] = labelencoder.fit_transform(schdist_df['instlevel'])
schdist_df = schdist_df.drop(columns=['instlevel'])
schdist_df

revtotal  member  overallaccountscore  activitysum  revperstudent  \
0      9963425.41     771                 76.3     553604.0   12922.730752   
1      9963425.41     771                 76.3     553604.0   12922.730752   
2      9963425.41     771                 76.3     553604.0   12922.730752   
3      9963425.41     771                 76.3     553604.0   12922.730752   
4      9963425.41     771                 76.3     553604.0   12922.730752   
...           ...     ...                  ...          ...            ...   
4365  15548503.74    1325                 84.2    1120235.0   11734.719804   
4366  15548503.74    1325                 84.2    1120235.0   11734.719804   
4367  15548503.74    1325                 84.2    1120235.0   11734.719804   
4368  15548503.74    1325                 84.2    1120235.0   11734.719804   
4369  15548503.74    1325                 84.2    1120235.0   11734.719804   

      diststudachievescore  diststudentgrowthscore  pctlep  pctwhite  pctswd  \
0                     50.6                    69.9   0.308     0.493   0.130   
1                     50.6                    69.9   0.308     0.493   0.130   
2                     50.6                    69.9   0.308     0.493   0.130   
3                     50.6                    69.9   0.308     0.493   0.130   
4                     50.6                    69.9   0.308     0.493   0.130   
...                    ...                     ...     ...       ...     ...   
4365                  88.1                    73.6   0.050     0.876   0.102   
4366                  88.1                    73.6   0.050     0.876   0.102   
4367                  88.1                    73.6   0.050     0.876   0.102   
4368                  88.1                    73.6   0.050     0.876   0.102   
4369                  88.1                    73.6   0.050     0.876   0.102   

      pctecondisad  groupcount  studentcount       instloc  initenrollcode  \
0            0.685          31            12      In-State               0   
1            0.685          31             6      In-State               0   
2            0.685          31             4      In-State               0   
3            0.685          31             3      In-State               2   
4            0.685          31             1      In-State               2   
...            ...         ...           ...           ...             ...   
4365         0.200         100             3      Multiple               0   
4366         0.200         100             4  Out-of-State               0   
4367         0.200         100             1      In-State               1   
4368         0.200         100             1      In-State               1   
4369         0.200         100             6      In-State               2   

      instlevelcode  
0                 0  
1                 1  
2                 2  
3                 0  
4                 1  
...             ...  
4365              2  
4366              1  
4367              0  
4368              1  
4369              0  

[4370 rows x 16 columns]

In [22]:
# Encode 'instloc' column
schdist_df['instloccode'] = labelencoder.fit_transform(schdist_df['instloc'])
schdist_df = schdist_df.drop(columns=['instloc'])
schdist_df

revtotal  member  overallaccountscore  activitysum  revperstudent  \
0      9963425.41     771                 76.3     553604.0   12922.730752   
1      9963425.41     771                 76.3     553604.0   12922.730752   
2      9963425.41     771                 76.3     553604.0   12922.730752   
3      9963425.41     771                 76.3     553604.0   12922.730752   
4      9963425.41     771                 76.3     553604.0   12922.730752   
...           ...     ...                  ...          ...            ...   
4365  15548503.74    1325                 84.2    1120235.0   11734.719804   
4366  15548503.74    1325                 84.2    1120235.0   11734.719804   
4367  15548503.74    1325                 84.2    1120235.0   11734.719804   
4368  15548503.74    1325                 84.2    1120235.0   11734.719804   
4369  15548503.74    1325                 84.2    1120235.0   11734.719804   

      diststudachievescore  diststudentgrowthscore  pctlep  pctwhite  pctswd  \
0                     50.6                    69.9   0.308     0.493   0.130   
1                     50.6                    69.9   0.308     0.493   0.130   
2                     50.6                    69.9   0.308     0.493   0.130   
3                     50.6                    69.9   0.308     0.493   0.130   
4                     50.6                    69.9   0.308     0.493   0.130   
...                    ...                     ...     ...       ...     ...   
4365                  88.1                    73.6   0.050     0.876   0.102   
4366                  88.1                    73.6   0.050     0.876   0.102   
4367                  88.1                    73.6   0.050     0.876   0.102   
4368                  88.1                    73.6   0.050     0.876   0.102   
4369                  88.1                    73.6   0.050     0.876   0.102   

      pctecondisad  groupcount  studentcount  initenrollcode  instlevelcode  \
0            0.685          31            12               0              0   
1            0.685          31             6               0              1   
2            0.685          31             4               0              2   
3            0.685          31             3               2              0   
4            0.685          31             1               2              1   
...            ...         ...           ...             ...            ...   
4365         0.200         100             3               0              2   
4366         0.200         100             4               0              1   
4367         0.200         100             1               1              0   
4368         0.200         100             1               1              1   
4369         0.200         100             6               2              0   

      instloccode  
0               0  
1               0  
2               0  
3               0  
4               0  
...           ...  
4365            1  
4366            2  
4367            0  
4368            0  
4369            0  

[4370 rows x 16 columns]

In [52]:
schdist_df[:] = np.nan_to_num(schdist_df)

In [53]:
# Define the features set.
X = schdist_df.copy()
X = X.drop("revperstudent", axis=1)
X.head()

index    revtotal  member  overallaccountscore  activitysum  \
0    0.0  9963425.41   771.0                 76.3     553604.0   
1    1.0  9963425.41   771.0                 76.3     553604.0   
2    2.0  9963425.41   771.0                 76.3     553604.0   
3    3.0  9963425.41   771.0                 76.3     553604.0   
4    4.0  9963425.41   771.0                 76.3     553604.0   

   diststudachievescore  diststudentgrowthscore  pctlep  pctwhite  pctswd  \
0                  50.6                    69.9   0.308     0.493    0.13   
1                  50.6                    69.9   0.308     0.493    0.13   
2                  50.6                    69.9   0.308     0.493    0.13   
3                  50.6                    69.9   0.308     0.493    0.13   
4                  50.6                    69.9   0.308     0.493    0.13   

   pctecondisad  groupcount  studentcount  initenrollcode  instlevelcode  \
0         0.685        31.0          12.0             0.0            0.0   
1         0.685        31.0           6.0             0.0            1.0   
2         0.685        31.0           4.0             0.0            2.0   
3         0.685        31.0           3.0             2.0            0.0   
4         0.685        31.0           1.0             2.0            1.0   

   instloccode  
0          0.0  
1          0.0  
2          0.0  
3          0.0  
4          0.0

In [54]:
schdist_df.columns

Index(['index', 'revtotal', 'member', 'overallaccountscore', 'activitysum',
       'revperstudent', 'diststudachievescore', 'diststudentgrowthscore',
       'pctlep', 'pctwhite', 'pctswd', 'pctecondisad', 'groupcount',
       'studentcount', 'initenrollcode', 'instlevelcode', 'instloccode'],
      dtype='object')

In [55]:
# Define the target set.
y = schdist_df["revperstudent"].ravel()
y[:5]

array([12922.73075227, 12922.73075227, 12922.73075227, 12922.73075227,
       12922.73075227])

In [56]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [57]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [58]:
# Create a random forest classifier.
rf_model = RandomForestRegressor(n_estimators=128, random_state=78) 

In [59]:
X_train_scaled.astype('float32')

array([[-0.57464427,  0.02043715,  0.07256612, ...,  0.45322752,
        -1.0933856 , -0.8009749 ],
       [-0.802867  , -0.4166852 , -0.43126455, ..., -0.73495376,
         0.1789953 , -0.8009749 ],
       [-1.1368514 , -0.4139019 , -0.43557653, ...,  0.45322752,
        -1.0933856 , -0.8009749 ],
       ...,
       [ 0.42094746, -0.38837138, -0.40539262, ...,  1.6414088 ,
        -1.0933856 , -0.8009749 ],
       [ 1.5278673 , -0.03034643, -0.00320168, ..., -0.73495376,
         1.4513761 ,  0.37923858],
       [-1.3873397 , -0.40767133, -0.4228086 , ...,  0.45322752,
        -1.0933856 , -0.8009749 ]], dtype=float32)

In [60]:
# Fixing nan and infinite values
np.nan_to_num(X_train_scaled)

array([[-0.57464427,  0.02043715,  0.07256612, ...,  0.45322751,
        -1.09338555, -0.80097492],
       [-0.80286697, -0.41668519, -0.43126455, ..., -0.73495373,
         0.17899529, -0.80097492],
       [-1.13685142, -0.41390191, -0.43557654, ...,  0.45322751,
        -1.09338555, -0.80097492],
       ...,
       [ 0.42094746, -0.38837139, -0.40539262, ...,  1.64140876,
        -1.09338555, -0.80097492],
       [ 1.52786733, -0.03034643, -0.00320168, ..., -0.73495373,
         1.45137613,  0.37923857],
       [-1.38733975, -0.40767133, -0.42280857, ...,  0.45322751,
        -1.09338555, -0.80097492]])

In [61]:
y_train.astype('float32')

array([13115.869, 11809.745, 13854.032, ..., 13479.786, 13572.817,
       12455.454], dtype=float32)

In [62]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [66]:
# Making predictions using the testing data.
y_pred = rf_model.predict(X_test_scaled)

In [69]:
# show mean absolute error and mean squared error
print('MAE: ', mean_absolute_error(y_test, y_pred))
print('MSE: ', mean_squared_error(y_test, y_pred))

MAE:  23.016518964769116
MSE:  16161.928905607292


In [73]:
# Verify model doesn't overfit (0.75 to 1.0 is acceptable)
rf_oob = RandomForestRegressor(oob_score=True)
rf_oob.fit(X_train_scaled, y_train)
print(rf_oob.oob_score_)

0.9942766124847207


In [74]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([2.19552751e-02, 1.53781214e-01, 3.13574846e-01, 2.53183232e-02,
       5.31458412e-02, 3.22136625e-02, 1.03083968e-01, 3.53891612e-02,
       1.31380870e-01, 3.79983815e-02, 6.59090078e-02, 2.58219246e-02,
       2.57425632e-04, 3.26995275e-05, 5.39852426e-05, 8.34137238e-05])

In [75]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.3135748463797742, 'member'),
 (0.15378121375581427, 'revtotal'),
 (0.13138087020949543, 'pctwhite'),
 (0.10308396842455163, 'diststudentgrowthscore'),
 (0.06590900780274198, 'pctecondisad'),
 (0.05314584118682375, 'activitysum'),
 (0.03799838147453878, 'pctswd'),
 (0.03538916119891505, 'pctlep'),
 (0.03221366253652074, 'diststudachievescore'),
 (0.025821924639661955, 'groupcount'),
 (0.02531832319652623, 'overallaccountscore'),
 (0.021955275069210526, 'index'),
 (0.00025742563151718776, 'studentcount'),
 (8.341372382842613e-05, 'instloccode'),
 (5.398524256359828e-05, 'instlevelcode'),
 (3.269952751634118e-05, 'initenrollcode')]